language: python
python:
  - "3.5"
branches:
  only:
    - master
services:
  - docker
env:
  - DOCKER_BUILD_FLAGS="--pull --no-cache"
sudo: required
install:
  - pip install -r rootfs/dev_requirements.txt
script:
  - make test docker-build
